# Generated by Django 5.0.1 on 2024-01-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_partyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='total_allowed_guest',
            field=models.SmallIntegerField(default=10),
        ),
    ]
