# Generated by Django 5.0.1 on 2024-01-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_party_total_allowed_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyrequest',
            name='text',
            field=models.CharField(default='Prazno', max_length=1024),
        ),
    ]
