# Generated by Django 5.0.1 on 2024-01-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_partyrequest_text'),
        ('app', '0004_user_date_of_birth'),
    ]

    operations = [
    ]
