# Generated by Django 5.0.1 on 2024-01-25 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_merge_0004_partyrequest_text_0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_poster_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.partyposters'),
        ),
        migrations.AlterField(
            model_name='partyguest',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.party'),
        ),
        migrations.AlterField(
            model_name='partyguest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='partyrequest',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.party'),
        ),
        migrations.AlterField(
            model_name='partyrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recension',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.party'),
        ),
        migrations.AlterField(
            model_name='recension',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
