# Generated by Django 5.0.1 on 2024-01-25 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_party_created_by_alter_party_party_poster_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrequest',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.party'),
        ),
        migrations.AlterField(
            model_name='partyrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
