# Generated by Django 5.0.1 on 2024-01-25 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_partyrequest_party_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='party',
            name='party_poster_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.partyposters'),
        ),
        migrations.AlterField(
            model_name='partyguest',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.party'),
        ),
        migrations.AlterField(
            model_name='partyguest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recension',
            name='party_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.party'),
        ),
        migrations.AlterField(
            model_name='recension',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
