# Generated by Django 5.0.1 on 2024-01-27 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_party_created_by_alter_party_party_poster_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='starts_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
